package com.ankamagames.dofus.misc.lists
{
    import com.ankamagames.dofus.datacenter.abuse.*;
    import com.ankamagames.dofus.datacenter.alignments.*;
    import com.ankamagames.dofus.datacenter.almanax.*;
    import com.ankamagames.dofus.datacenter.ambientSounds.*;
    import com.ankamagames.dofus.datacenter.breeds.*;
    import com.ankamagames.dofus.datacenter.challenges.*;
    import com.ankamagames.dofus.datacenter.communication.*;
    import com.ankamagames.dofus.datacenter.documents.*;
    import com.ankamagames.dofus.datacenter.effects.*;
    import com.ankamagames.dofus.datacenter.externalnotifications.*;
    import com.ankamagames.dofus.datacenter.guild.*;
    import com.ankamagames.dofus.datacenter.houses.*;
    import com.ankamagames.dofus.datacenter.interactives.*;
    import com.ankamagames.dofus.datacenter.items.*;
    import com.ankamagames.dofus.datacenter.jobs.*;
    import com.ankamagames.dofus.datacenter.livingObjects.*;
    import com.ankamagames.dofus.datacenter.misc.*;
    import com.ankamagames.dofus.datacenter.monsters.*;
    import com.ankamagames.dofus.datacenter.mounts.*;
    import com.ankamagames.dofus.datacenter.notifications.*;
    import com.ankamagames.dofus.datacenter.npcs.*;
    import com.ankamagames.dofus.datacenter.quest.*;
    import com.ankamagames.dofus.datacenter.quest.objectives.*;
    import com.ankamagames.dofus.datacenter.servers.*;
    import com.ankamagames.dofus.datacenter.sounds.*;
    import com.ankamagames.dofus.datacenter.spells.*;
    import com.ankamagames.dofus.datacenter.world.*;

    public class GameDataList extends Object
    {
        public static const server:Server = null;
        public static const serverCommunity:ServerCommunity = null;
        public static const serverGameType:ServerGameType = null;
        public static const serverPopulation:ServerPopulation = null;
        public static const monster:Monster = null;
        public static const monsterGrade:MonsterGrade = null;
        public static const monsterRace:MonsterRace = null;
        public static const monsterSuperRace:MonsterSuperRace = null;
        public static const notification:Notification = null;
        public static const spell:Spell = null;
        public static const effect:Effect = null;
        public static const effectInstance:EffectInstance = null;
        public static const spellLevel:SpellLevel = null;
        public static const spellType:SpellType = null;
        public static const spellState:SpellState = null;
        public static const breed:Breed = null;
        public static const superArea:SuperArea = null;
        public static const area:Area = null;
        public static const wolrdMap:WorldMap = null;
        public static const subArea:SubArea = null;
        public static const hint:Hint = null;
        public static const hintCategory:HintCategory = null;
        public static const mapPosition:MapPosition = null;
        public static const mapReference:MapReference = null;
        public static const item:Item = null;
        public static const chatChannel:ChatChannel = null;
        public static const weapon:Weapon = null;
        public static const job:Job = null;
        public static const skill:Skill = null;
        public static const recipe:Recipe = null;
        public static const itemSet:ItemSet = null;
        public static const month:Month = null;
        public static const npc:Npc = null;
        public static const npcAction:NpcAction = null;
        public static const npcMessage:NpcMessage = null;
        public static const infoMessage:InfoMessage = null;
        public static const taxCollectorFirstname:TaxCollectorFirstname = null;
        public static const taxCollectorName:TaxCollectorName = null;
        public static const challenge:Challenge = null;
        public static const alignmentBalance:AlignmentBalance = null;
        public static const alignmentEffect:AlignmentEffect = null;
        public static const alignmentGift:AlignmentGift = null;
        public static const alignmentOrder:AlignmentOrder = null;
        public static const alignmentRank:AlignmentRank = null;
        public static const alignmentRankJntGift:AlignmentRankJntGift = null;
        public static const alignmentSide:AlignmentSide = null;
        public static const alignmentTitle:AlignmentTitle = null;
        public static const ambientSound:AmbientSound = null;
        public static const house:House = null;
        public static const rankName:RankName = null;
        public static const emblemBackground:EmblemBackground = null;
        public static const emblemSymbol:EmblemSymbol = null;
        public static const emblemSymbolCategory:EmblemSymbolCategory = null;
        public static const interactive:Interactive = null;
        public static const itemType:ItemType = null;
        public static const emoticon:Emoticon = null;
        public static const smiley:Smiley = null;
        public static const quest:Quest = null;
        public static const questCategory:QuestCategory = null;
        public static const questStep:QuestStep = null;
        public static const questStepRewards:QuestStepRewards = null;
        public static const questObjective:QuestObjective = null;
        public static const questObjectiveType:QuestObjectiveType = null;
        public static const questObjectiveBringItemToNpc:QuestObjectiveBringItemToNpc = null;
        public static const questObjectiveBringSoulToNpc:QuestObjectiveBringSoulToNpc = null;
        public static const questObjectiveDiscoverMap:QuestObjectiveDiscoverMap = null;
        public static const questObjectiveDiscoverSubArea:QuestObjectiveDiscoverSubArea = null;
        public static const questObjectiveDuelSpecificPlayer:QuestObjectiveDuelSpecificPlayer = null;
        public static const questObjectiveFightMonster:QuestObjectiveFightMonster = null;
        public static const questObjectiveMultiFightMonster:QuestObjectiveMultiFightMonster = null;
        public static const questObjectiveFreeForm:QuestObjectiveFreeForm = null;
        public static const questObjectiveGoToNpc:QuestObjectiveGoToNpc = null;
        public static const mount:Mount = null;
        public static const mountBehavior:MountBehavior = null;
        public static const mountRideFood:RideFood = null;
        public static const pet:Pet = null;
        public static const document:Document = null;
        public static const appearance:Appearance = null;
        public static const speakingItemsTrigger:SpeakingItemsTrigger = null;
        public static const speakingItemText:SpeakingItemText = null;
        public static const livingObjectSkinJntMood:LivingObjectSkinJntMood = null;
        public static const abuseReasons:AbuseReasons = null;
        public static const tips:Tips = null;
        public static const pack:Pack = null;
        public static const optionalFeature:OptionalFeature = null;
        public static const censoredWord:CensoredWord = null;
        public static const title:Title = null;
        public static const dungeon:Dungeon = null;
        public static const url:Url = null;
        public static const miniBoss:MonsterMiniBoss = null;
        public static const soundAnimation:SoundAnimation = null;
        public static const soundBones:SoundBones = null;
        public static const stealthBones:StealthBones = null;
        public static const typeAction:TypeAction = null;
        public static const externalNotification:ExternalNotification = null;
        public static const almanaxCalendar:AlmanaxCalendar = null;

        public function GameDataList()
        {
            return;
        }// end function

    }
}
