package com.ankamagames.berilia.utils.web
{
   public class MimeTypeHelper extends Object
   {
      
      public function MimeTypeHelper() {
         super();
      }
      
      public static function getMimeType(param1:String) : String {
         var mimeNode:XML = null;
         var fileExtension:String = param1;
         mimeNode = MimeTypeHelper.mimetypeXml.mimeType.(attribute("fileExtension") == fileExtension)[0];
         if(mimeNode)
         {
            return mimeNode.@type;
         }
         return null;
      }
      
      public static const mimetypeXml:XML = <mimeTypes>
  <mimeType fileExtension="3dm" type="x-world/x-3dmf"/>
  <mimeType fileExtension="3dmf" type="x-world/x-3dmf"/>
  <mimeType fileExtension="a" type="application/octet-stream"/>
  <mimeType fileExtension="aab" type="application/x-authorware-bin"/>
  <mimeType fileExtension="aam" type="application/x-authorware-map"/>
  <mimeType fileExtension="aas" type="application/x-authorware-seg"/>
  <mimeType fileExtension="abc" type="text/vnd.abc"/>
  <mimeType fileExtension="acgi" type="text/html"/>
  <mimeType fileExtension="afl" type="video/animaflex"/>
  <mimeType fileExtension="ai" type="application/postscript"/>
  <mimeType fileExtension="aif" type="audio/aiff"/>
  <mimeType fileExtension="aif" type="audio/x-aiff"/>
  <mimeType fileExtension="aifc" type="audio/aiff"/>
  <mimeType fileExtension="aifc" type="audio/x-aiff"/>
  <mimeType fileExtension="aiff" type="audio/aiff"/>
  <mimeType fileExtension="aiff" type="audio/x-aiff"/>
  <mimeType fileExtension="aim" type="application/x-aim"/>
  <mimeType fileExtension="aip" type="text/x-audiosoft-intra"/>
  <mimeType fileExtension="ani" type="application/x-navi-animation"/>
  <mimeType fileExtension="aos" type="application/x-nokia-9000-communicator-add-on-software"/>
  <mimeType fileExtension="aps" type="application/mime"/>
  <mimeType fileExtension="arc" type="application/octet-stream"/>
  <mimeType fileExtension="arj" type="application/arj"/>
  <mimeType fileExtension="arj" type="application/octet-stream"/>
  <mimeType fileExtension="art" type="image/x-jg"/>
  <mimeType fileExtension="asf" type="video/x-ms-asf"/>
  <mimeType fileExtension="asm" type="text/x-asm"/>
  <mimeType fileExtension="asp" type="text/asp"/>
  <mimeType fileExtension="asx" type="application/x-mplayer2"/>
  <mimeType fileExtension="asx" type="video/x-ms-asf"/>
  <mimeType fileExtension="asx" type="video/x-ms-asf-plugin"/>
  <mimeType fileExtension="au" type="audio/basic"/>
  <mimeType fileExtension="au" type="audio/x-au"/>
  <mimeType fileExtension="avi" type="application/x-troff-msvideo"/>
  <mimeType fileExtension="avi" type="video/avi"/>
  <mimeType fileExtension="avi" type="video/msvideo"/>
  <mimeType fileExtension="avi" type="video/x-msvideo"/>
  <mimeType fileExtension="avs" type="video/avs-video"/>
  <mimeType fileExtension="bcpio" type="application/x-bcpio"/>
  <mimeType fileExtension="bin" type="application/mac-binary"/>
  <mimeType fileExtension="bin" type="application/macbinary"/>
  <mimeType fileExtension="bin" type="application/octet-stream"/>
  <mimeType fileExtension="bin" type="application/x-binary"/>
  <mimeType fileExtension="bin" type="application/x-macbinary"/>
  <mimeType fileExtension="bm" type="image/bmp"/>
  <mimeType fileExtension="bmp" type="image/bmp"/>
  <mimeType fileExtension="bmp" type="image/x-windows-bmp"/>
  <mimeType fileExtension="boo" type="application/book"/>
  <mimeType fileExtension="book" type="application/book"/>
  <mimeType fileExtension="boz" type="application/x-bzip2"/>
  <mimeType fileExtension="bsh" type="application/x-bsh"/>
  <mimeType fileExtension="bz" type="application/x-bzip"/>
  <mimeType fileExtension="bz2" type="application/x-bzip2"/>
  <mimeType fileExtension="c" type="text/plain"/>
  <mimeType fileExtension="c" type="text/x-c"/>
  <mimeType fileExtension="c++" type="text/plain"/>
  <mimeType fileExtension="cat" type="application/vnd.ms-pki.seccat"/>
  <mimeType fileExtension="cc" type="text/plain"/>
  <mimeType fileExtension="cc" type="text/x-c"/>
  <mimeType fileExtension="ccad" type="application/clariscad"/>
  <mimeType fileExtension="cco" type="application/x-cocoa"/>
  <mimeType fileExtension="cdf" type="application/cdf"/>
  <mimeType fileExtension="cdf" type="application/x-cdf"/>
  <mimeType fileExtension="cdf" type="application/x-netcdf"/>
  <mimeType fileExtension="cer" type="application/pkix-cert"/>
  <mimeType fileExtension="cer" type="application/x-x509-ca-cert"/>
  <mimeType fileExtension="cha" type="application/x-chat"/>
  <mimeType fileExtension="chat" type="application/x-chat"/>
  <mimeType fileExtension="class" type="application/java"/>
  <mimeType fileExtension="class" type="application/java-byte-code"/>
  <mimeType fileExtension="class" type="application/x-java-class"/>
  <mimeType fileExtension="com" type="application/octet-stream"/>
  <mimeType fileExtension="com" type="text/plain"/>
  <mimeType fileExtension="conf" type="text/plain"/>
  <mimeType fileExtension="cpio" type="application/x-cpio"/>
  <mimeType fileExtension="cpp" type="text/x-c"/>
  <mimeType fileExtension="cpt" type="application/mac-compactpro"/>
  <mimeType fileExtension="cpt" type="application/x-compactpro"/>
  <mimeType fileExtension="cpt" type="application/x-cpt"/>
  <mimeType fileExtension="crl" type="application/pkcs-crl"/>
  <mimeType fileExtension="crl" type="application/pkix-crl"/>
  <mimeType fileExtension="crt" type="application/pkix-cert"/>
  <mimeType fileExtension="crt" type="application/x-x509-ca-cert"/>
  <mimeType fileExtension="crt" type="application/x-x509-user-cert"/>
  <mimeType fileExtension="csh" type="application/x-csh"/>
  <mimeType fileExtension="csh" type="text/x-script.csh"/>
  <mimeType fileExtension="css" type="application/x-pointplus"/>
  <mimeType fileExtension="css" type="text/css"/>
  <mimeType fileExtension="cxx" type="text/plain"/>
  <mimeType fileExtension="dcr" type="application/x-director"/>
  <mimeType fileExtension="deepv" type="application/x-deepv"/>
  <mimeType fileExtension="def" type="text/plain"/>
  <mimeType fileExtension="der" type="application/x-x509-ca-cert"/>
  <mimeType fileExtension="dif" type="video/x-dv"/>
  <mimeType fileExtension="dir" type="application/x-director"/>
  <mimeType fileExtension="dl" type="video/dl"/>
  <mimeType fileExtension="dl" type="video/x-dl"/>
  <mimeType fileExtension="doc" type="application/msword"/>
  <mimeType fileExtension="dot" type="application/msword"/>
  <mimeType fileExtension="dp" type="application/commonground"/>
  <mimeType fileExtension="drw" type="application/drafting"/>
  <mimeType fileExtension="dump" type="application/octet-stream"/>
  <mimeType fileExtension="dv" type="video/x-dv"/>
  <mimeType fileExtension="dvi" type="application/x-dvi"/>
  <mimeType fileExtension="dwf" type="drawing/x-dwf(old)"/>
  <mimeType fileExtension="dwf" type="model/vnd.dwf"/>
  <mimeType fileExtension="dwg" type="application/acad"/>
  <mimeType fileExtension="dwg" type="image/vnd.dwg"/>
  <mimeType fileExtension="dwg" type="image/x-dwg"/>
  <mimeType fileExtension="dxf" type="application/dxf"/>
  <mimeType fileExtension="dxf" type="image/vnd.dwg"/>
  <mimeType fileExtension="dxf" type="image/x-dwg"/>
  <mimeType fileExtension="dxr" type="application/x-director"/>
  <mimeType fileExtension="el" type="text/x-script.elisp"/>
  <mimeType fileExtension="elc" type="application/x-bytecode.elisp(compiledelisp)"/>
  <mimeType fileExtension="elc" type="application/x-elc"/>
  <mimeType fileExtension="env" type="application/x-envoy"/>
  <mimeType fileExtension="eps" type="application/postscript"/>
  <mimeType fileExtension="es" type="application/x-esrehber"/>
  <mimeType fileExtension="etx" type="text/x-setext"/>
  <mimeType fileExtension="evy" type="application/envoy"/>
  <mimeType fileExtension="evy" type="application/x-envoy"/>
  <mimeType fileExtension="exe" type="application/octet-stream"/>
  <mimeType fileExtension="f" type="text/plain"/>
  <mimeType fileExtension="f" type="text/x-fortran"/>
  <mimeType fileExtension="f77" type="text/x-fortran"/>
  <mimeType fileExtension="f90" type="text/plain"/>
  <mimeType fileExtension="f90" type="text/x-fortran"/>
  <mimeType fileExtension="fdf" type="application/vnd.fdf"/>
  <mimeType fileExtension="fif" type="application/fractals"/>
  <mimeType fileExtension="fif" type="image/fif"/>
  <mimeType fileExtension="fli" type="video/fli"/>
  <mimeType fileExtension="fli" type="video/x-fli"/>
  <mimeType fileExtension="flo" type="image/florian"/>
  <mimeType fileExtension="flx" type="text/vnd.fmi.flexstor"/>
  <mimeType fileExtension="fmf" type="video/x-atomic3d-feature"/>
  <mimeType fileExtension="for" type="text/plain"/>
  <mimeType fileExtension="for" type="text/x-fortran"/>
  <mimeType fileExtension="fpx" type="image/vnd.fpx"/>
  <mimeType fileExtension="fpx" type="image/vnd.net-fpx"/>
  <mimeType fileExtension="frl" type="application/freeloader"/>
  <mimeType fileExtension="funk" type="audio/make"/>
  <mimeType fileExtension="g" type="text/plain"/>
  <mimeType fileExtension="g3" type="image/g3fax"/>
  <mimeType fileExtension="gif" type="image/gif"/>
  <mimeType fileExtension="gl" type="video/gl"/>
  <mimeType fileExtension="gl" type="video/x-gl"/>
  <mimeType fileExtension="gsd" type="audio/x-gsm"/>
  <mimeType fileExtension="gsm" type="audio/x-gsm"/>
  <mimeType fileExtension="gsp" type="application/x-gsp"/>
  <mimeType fileExtension="gss" type="application/x-gss"/>
  <mimeType fileExtension="gtar" type="application/x-gtar"/>
  <mimeType fileExtension="gz" type="application/x-compressed"/>
  <mimeType fileExtension="gz" type="application/x-gzip"/>
  <mimeType fileExtension="gzip" type="application/x-gzip"/>
  <mimeType fileExtension="gzip" type="multipart/x-gzip"/>
  <mimeType fileExtension="h" type="text/plain"/>
  <mimeType fileExtension="h" type="text/x-h"/>
  <mimeType fileExtension="hdf" type="application/x-hdf"/>
  <mimeType fileExtension="help" type="application/x-helpfile"/>
  <mimeType fileExtension="hgl" type="application/vnd.hp-hpgl"/>
  <mimeType fileExtension="hh" type="text/plain"/>
  <mimeType fileExtension="hh" type="text/x-h"/>
  <mimeType fileExtension="hlb" type="text/x-script"/>
  <mimeType fileExtension="hlp" type="application/hlp"/>
  <mimeType fileExtension="hlp" type="application/x-helpfile"/>
  <mimeType fileExtension="hlp" type="application/x-winhelp"/>
  <mimeType fileExtension="hpg" type="application/vnd.hp-hpgl"/>
  <mimeType fileExtension="hpgl" type="application/vnd.hp-hpgl"/>
  <mimeType fileExtension="hqx" type="application/binhex"/>
  <mimeType fileExtension="hqx" type="application/binhex4"/>
  <mimeType fileExtension="hqx" type="application/mac-binhex"/>
  <mimeType fileExtension="hqx" type="application/mac-binhex40"/>
  <mimeType fileExtension="hqx" type="application/x-binhex40"/>
  <mimeType fileExtension="hqx" type="application/x-mac-binhex40"/>
  <mimeType fileExtension="hta" type="application/hta"/>
  <mimeType fileExtension="htc" type="text/x-component"/>
  <mimeType fileExtension="htm" type="text/html"/>
  <mimeType fileExtension="html" type="text/html"/>
  <mimeType fileExtension="htmls" type="text/html"/>
  <mimeType fileExtension="htt" type="text/webviewhtml"/>
  <mimeType fileExtension="htx" type="text/html"/>
  <mimeType fileExtension="ice" type="x-conference/x-cooltalk"/>
  <mimeType fileExtension="ico" type="image/x-icon"/>
  <mimeType fileExtension="idc" type="text/plain"/>
  <mimeType fileExtension="ief" type="image/ief"/>
  <mimeType fileExtension="iefs" type="image/ief"/>
  <mimeType fileExtension="iges" type="application/iges"/>
  <mimeType fileExtension="iges" type="model/iges"/>
  <mimeType fileExtension="igs" type="application/iges"/>
  <mimeType fileExtension="igs" type="model/iges"/>
  <mimeType fileExtension="ima" type="application/x-ima"/>
  <mimeType fileExtension="imap" type="application/x-httpd-imap"/>
  <mimeType fileExtension="inf" type="application/inf"/>
  <mimeType fileExtension="ins" type="application/x-internett-signup"/>
  <mimeType fileExtension="ip" type="application/x-ip2"/>
  <mimeType fileExtension="isu" type="video/x-isvideo"/>
  <mimeType fileExtension="it" type="audio/it"/>
  <mimeType fileExtension="iv" type="application/x-inventor"/>
  <mimeType fileExtension="ivr" type="i-world/i-vrml"/>
  <mimeType fileExtension="ivy" type="application/x-livescreen"/>
  <mimeType fileExtension="jam" type="audio/x-jam"/>
  <mimeType fileExtension="jav" type="text/plain"/>
  <mimeType fileExtension="jav" type="text/x-java-source"/>
  <mimeType fileExtension="java" type="text/plain"/>
  <mimeType fileExtension="java" type="text/x-java-source"/>
  <mimeType fileExtension="jcm" type="application/x-java-commerce"/>
  <mimeType fileExtension="jfif" type="image/jpeg"/>
  <mimeType fileExtension="jfif" type="image/pjpeg"/>
  <mimeType fileExtension="jfif-tbnl" type="image/jpeg"/>
  <mimeType fileExtension="jpe" type="image/jpeg"/>
  <mimeType fileExtension="jpe" type="image/pjpeg"/>
  <mimeType fileExtension="jpeg" type="image/jpeg"/>
  <mimeType fileExtension="jpeg" type="image/pjpeg"/>
  <mimeType fileExtension="jpg" type="image/jpeg"/>
  <mimeType fileExtension="jpg" type="image/pjpeg"/>
  <mimeType fileExtension="jps" type="image/x-jps"/>
  <mimeType fileExtension="js" type="application/x-javascript"/>
  <mimeType fileExtension="jut" type="image/jutvision"/>
  <mimeType fileExtension="kar" type="audio/midi"/>
  <mimeType fileExtension="kar" type="music/x-karaoke"/>
  <mimeType fileExtension="ksh" type="application/x-ksh"/>
  <mimeType fileExtension="ksh" type="text/x-script.ksh"/>
  <mimeType fileExtension="la" type="audio/nspaudio"/>
  <mimeType fileExtension="la" type="audio/x-nspaudio"/>
  <mimeType fileExtension="lam" type="audio/x-liveaudio"/>
  <mimeType fileExtension="latex" type="application/x-latex"/>
  <mimeType fileExtension="lha" type="application/lha"/>
  <mimeType fileExtension="lha" type="application/octet-stream"/>
  <mimeType fileExtension="lha" type="application/x-lha"/>
  <mimeType fileExtension="lhx" type="application/octet-stream"/>
  <mimeType fileExtension="list" type="text/plain"/>
  <mimeType fileExtension="lma" type="audio/nspaudio"/>
  <mimeType fileExtension="lma" type="audio/x-nspaudio"/>
  <mimeType fileExtension="log" type="text/plain"/>
  <mimeType fileExtension="lsp" type="application/x-lisp"/>
  <mimeType fileExtension="lsp" type="text/x-script.lisp"/>
  <mimeType fileExtension="lst" type="text/plain"/>
  <mimeType fileExtension="lsx" type="text/x-la-asf"/>
  <mimeType fileExtension="ltx" type="application/x-latex"/>
  <mimeType fileExtension="lzh" type="application/octet-stream"/>
  <mimeType fileExtension="lzh" type="application/x-lzh"/>
  <mimeType fileExtension="lzx" type="application/lzx"/>
  <mimeType fileExtension="lzx" type="application/octet-stream"/>
  <mimeType fileExtension="lzx" type="application/x-lzx"/>
  <mimeType fileExtension="m" type="text/plain"/>
  <mimeType fileExtension="m" type="text/x-m"/>
  <mimeType fileExtension="m1v" type="video/mpeg"/>
  <mimeType fileExtension="m2a" type="audio/mpeg"/>
  <mimeType fileExtension="m2v" type="video/mpeg"/>
  <mimeType fileExtension="m3u" type="audio/x-mpequrl"/>
  <mimeType fileExtension="man" type="application/x-troff-man"/>
  <mimeType fileExtension="map" type="application/x-navimap"/>
  <mimeType fileExtension="mar" type="text/plain"/>
  <mimeType fileExtension="mbd" type="application/mbedlet"/>
  <mimeType fileExtension="mc$" type="application/x-magic-cap-package-1.0"/>
  <mimeType fileExtension="mcd" type="application/mcad"/>
  <mimeType fileExtension="mcd" type="application/x-mathcad"/>
  <mimeType fileExtension="mcf" type="image/vasa"/>
  <mimeType fileExtension="mcf" type="text/mcf"/>
  <mimeType fileExtension="mcp" type="application/netmc"/>
  <mimeType fileExtension="me" type="application/x-troff-me"/>
  <mimeType fileExtension="mht" type="message/rfc822"/>
  <mimeType fileExtension="mhtml" type="message/rfc822"/>
  <mimeType fileExtension="mid" type="application/x-midi"/>
  <mimeType fileExtension="mid" type="audio/midi"/>
  <mimeType fileExtension="mid" type="audio/x-mid"/>
  <mimeType fileExtension="mid" type="audio/x-midi"/>
  <mimeType fileExtension="mid" type="music/crescendo"/>
  <mimeType fileExtension="mid" type="x-music/x-midi"/>
  <mimeType fileExtension="midi" type="application/x-midi"/>
  <mimeType fileExtension="midi" type="audio/midi"/>
  <mimeType fileExtension="midi" type="audio/x-mid"/>
  <mimeType fileExtension="midi" type="audio/x-midi"/>
  <mimeType fileExtension="midi" type="music/crescendo"/>
  <mimeType fileExtension="midi" type="x-music/x-midi"/>
  <mimeType fileExtension="mif" type="application/x-frame"/>
  <mimeType fileExtension="mif" type="application/x-mif"/>
  <mimeType fileExtension="mime" type="message/rfc822"/>
  <mimeType fileExtension="mime" type="www/mime"/>
  <mimeType fileExtension="mjf" type="audio/x-vnd.audioexplosion.mjuicemediafile"/>
  <mimeType fileExtension="mjpg" type="video/x-motion-jpeg"/>
  <mimeType fileExtension="mm" type="application/base64"/>
  <mimeType fileExtension="mm" type="application/x-meme"/>
  <mimeType fileExtension="mme" type="application/base64"/>
  <mimeType fileExtension="mod" type="audio/mod"/>
  <mimeType fileExtension="mod" type="audio/x-mod"/>
  <mimeType fileExtension="moov" type="video/quicktime"/>
  <mimeType fileExtension="mov" type="video/quicktime"/>
  <mimeType fileExtension="movie" type="video/x-sgi-movie"/>
  <mimeType fileExtension="mp2" type="audio/mpeg"/>
  <mimeType fileExtension="mp2" type="audio/x-mpeg"/>
  <mimeType fileExtension="mp2" type="video/mpeg"/>
  <mimeType fileExtension="mp2" type="video/x-mpeg"/>
  <mimeType fileExtension="mp2" type="video/x-mpeq2a"/>
  <mimeType fileExtension="mp3" type="audio/mpeg3"/>
  <mimeType fileExtension="mp3" type="audio/x-mpeg-3"/>
  <mimeType fileExtension="mp3" type="video/mpeg"/>
  <mimeType fileExtension="mp3" type="video/x-mpeg"/>
  <mimeType fileExtension="mpa" type="audio/mpeg"/>
  <mimeType fileExtension="mpa" type="video/mpeg"/>
  <mimeType fileExtension="mpc" type="application/x-project"/>
  <mimeType fileExtension="mpe" type="video/mpeg"/>
  <mimeType fileExtension="mpeg" type="video/mpeg"/>
  <mimeType fileExtension="mpg" type="audio/mpeg"/>
  <mimeType fileExtension="mpg" type="video/mpeg"/>
  <mimeType fileExtension="mpga" type="audio/mpeg"/>
  <mimeType fileExtension="mpp" type="application/vnd.ms-project"/>
  <mimeType fileExtension="mpt" type="application/x-project"/>
  <mimeType fileExtension="mpv" type="application/x-project"/>
  <mimeType fileExtension="mpx" type="application/x-project"/>
  <mimeType fileExtension="mrc" type="application/marc"/>
  <mimeType fileExtension="ms" type="application/x-troff-ms"/>
  <mimeType fileExtension="mv" type="video/x-sgi-movie"/>
  <mimeType fileExtension="my" type="audio/make"/>
  <mimeType fileExtension="mzz" type="application/x-vnd.audioexplosion.mzz"/>
  <mimeType fileExtension="nap" type="image/naplps"/>
  <mimeType fileExtension="naplps" type="image/naplps"/>
  <mimeType fileExtension="nc" type="application/x-netcdf"/>
  <mimeType fileExtension="ncm" type="application/vnd.nokia.configuration-message"/>
  <mimeType fileExtension="nif" type="image/x-niff"/>
  <mimeType fileExtension="niff" type="image/x-niff"/>
  <mimeType fileExtension="nix" type="application/x-mix-transfer"/>
  <mimeType fileExtension="nsc" type="application/x-conference"/>
  <mimeType fileExtension="nvd" type="application/x-navidoc"/>
  <mimeType fileExtension="o" type="application/octet-stream"/>
  <mimeType fileExtension="oda" type="application/oda"/>
  <mimeType fileExtension="omc" type="application/x-omc"/>
  <mimeType fileExtension="omcd" type="application/x-omcdatamaker"/>
  <mimeType fileExtension="omcr" type="application/x-omcregerator"/>
  <mimeType fileExtension="p" type="text/x-pascal"/>
  <mimeType fileExtension="p10" type="application/pkcs10"/>
  <mimeType fileExtension="p10" type="application/x-pkcs10"/>
  <mimeType fileExtension="p12" type="application/pkcs-12"/>
  <mimeType fileExtension="p12" type="application/x-pkcs12"/>
  <mimeType fileExtension="p7a" type="application/x-pkcs7-signature"/>
  <mimeType fileExtension="p7c" type="application/pkcs7-mime"/>
  <mimeType fileExtension="p7c" type="application/x-pkcs7-mime"/>
  <mimeType fileExtension="p7m" type="application/pkcs7-mime"/>
  <mimeType fileExtension="p7m" type="application/x-pkcs7-mime"/>
  <mimeType fileExtension="p7r" type="application/x-pkcs7-certreqresp"/>
  <mimeType fileExtension="p7s" type="application/pkcs7-signature"/>
  <mimeType fileExtension="part" type="application/pro_eng"/>
  <mimeType fileExtension="pas" type="text/pascal"/>
  <mimeType fileExtension="pbm" type="image/x-portable-bitmap"/>
  <mimeType fileExtension="pcl" type="application/vnd.hp-pcl"/>
  <mimeType fileExtension="pcl" type="application/x-pcl"/>
  <mimeType fileExtension="pct" type="image/x-pict"/>
  <mimeType fileExtension="pcx" type="image/x-pcx"/>
  <mimeType fileExtension="pdb" type="chemical/x-pdb"/>
  <mimeType fileExtension="pdf" type="application/pdf"/>
  <mimeType fileExtension="pfunk" type="audio/make"/>
  <mimeType fileExtension="pfunk" type="audio/make.my.funk"/>
  <mimeType fileExtension="pgm" type="image/x-portable-graymap"/>
  <mimeType fileExtension="pgm" type="image/x-portable-greymap"/>
  <mimeType fileExtension="pic" type="image/pict"/>
  <mimeType fileExtension="pict" type="image/pict"/>
  <mimeType fileExtension="pkg" type="application/x-newton-compatible-pkg"/>
  <mimeType fileExtension="pko" type="application/vnd.ms-pki.pko"/>
  <mimeType fileExtension="pl" type="text/plain"/>
  <mimeType fileExtension="pl" type="text/x-script.perl"/>
  <mimeType fileExtension="plx" type="application/x-pixclscript"/>
  <mimeType fileExtension="pm" type="image/x-xpixmap"/>
  <mimeType fileExtension="pm" type="text/x-script.perl-module"/>
  <mimeType fileExtension="pm4" type="application/x-pagemaker"/>
  <mimeType fileExtension="pm5" type="application/x-pagemaker"/>
  <mimeType fileExtension="png" type="image/png"/>
  <mimeType fileExtension="pnm" type="application/x-portable-anymap"/>
  <mimeType fileExtension="pnm" type="image/x-portable-anymap"/>
  <mimeType fileExtension="pot" type="application/mspowerpoint"/>
  <mimeType fileExtension="pot" type="application/vnd.ms-powerpoint"/>
  <mimeType fileExtension="pov" type="model/x-pov"/>
  <mimeType fileExtension="ppa" type="application/vnd.ms-powerpoint"/>
  <mimeType fileExtension="ppm" type="image/x-portable-pixmap"/>
  <mimeType fileExtension="pps" type="application/mspowerpoint"/>
  <mimeType fileExtension="pps" type="application/vnd.ms-powerpoint"/>
  <mimeType fileExtension="ppt" type="application/mspowerpoint"/>
  <mimeType fileExtension="ppt" type="application/powerpoint"/>
  <mimeType fileExtension="ppt" type="application/vnd.ms-powerpoint"/>
  <mimeType fileExtension="ppt" type="application/x-mspowerpoint"/>
  <mimeType fileExtension="ppz" type="application/mspowerpoint"/>
  <mimeType fileExtension="pre" type="application/x-freelance"/>
  <mimeType fileExtension="prt" type="application/pro_eng"/>
  <mimeType fileExtension="ps" type="application/postscript"/>
  <mimeType fileExtension="psd" type="application/octet-stream"/>
  <mimeType fileExtension="pvu" type="paleovu/x-pv"/>
  <mimeType fileExtension="pwz" type="application/vnd.ms-powerpoint"/>
  <mimeType fileExtension="py" type="text/x-script.phyton"/>
  <mimeType fileExtension="pyc" type="applicaiton/x-bytecode.python"/>
  <mimeType fileExtension="qcp" type="audio/vnd.qcelp"/>
  <mimeType fileExtension="qd3" type="x-world/x-3dmf"/>
  <mimeType fileExtension="qd3d" type="x-world/x-3dmf"/>
  <mimeType fileExtension="qif" type="image/x-quicktime"/>
  <mimeType fileExtension="qt" type="video/quicktime"/>
  <mimeType fileExtension="qtc" type="video/x-qtc"/>
  <mimeType fileExtension="qti" type="image/x-quicktime"/>
  <mimeType fileExtension="qtif" type="image/x-quicktime"/>
  <mimeType fileExtension="ra" type="audio/x-pn-realaudio"/>
  <mimeType fileExtension="ra" type="audio/x-pn-realaudio-plugin"/>
  <mimeType fileExtension="ra" type="audio/x-realaudio"/>
  <mimeType fileExtension="ram" type="audio/x-pn-realaudio"/>
  <mimeType fileExtension="ras" type="application/x-cmu-raster"/>
  <mimeType fileExtension="ras" type="image/cmu-raster"/>
  <mimeType fileExtension="ras" type="image/x-cmu-raster"/>
  <mimeType fileExtension="rast" type="image/cmu-raster"/>
  <mimeType fileExtension="rexx" type="text/x-script.rexx"/>
  <mimeType fileExtension="rf" type="image/vnd.rn-realflash"/>
  <mimeType fileExtension="rgb" type="image/x-rgb"/>
  <mimeType fileExtension="rm" type="application/vnd.rn-realmedia"/>
  <mimeType fileExtension="rm" type="audio/x-pn-realaudio"/>
  <mimeType fileExtension="rmi" type="audio/mid"/>
  <mimeType fileExtension="rmm" type="audio/x-pn-realaudio"/>
  <mimeType fileExtension="rmp" type="audio/x-pn-realaudio"/>
  <mimeType fileExtension="rmp" type="audio/x-pn-realaudio-plugin"/>
  <mimeType fileExtension="rng" type="application/ringing-tones"/>
  <mimeType fileExtension="rng" type="application/vnd.nokia.ringing-tone"/>
  <mimeType fileExtension="rnx" type="application/vnd.rn-realplayer"/>
  <mimeType fileExtension="roff" type="application/x-troff"/>
  <mimeType fileExtension="rp" type="image/vnd.rn-realpix"/>
  <mimeType fileExtension="rpm" type="audio/x-pn-realaudio-plugin"/>
  <mimeType fileExtension="rt" type="text/richtext"/>
  <mimeType fileExtension="rt" type="text/vnd.rn-realtext"/>
  <mimeType fileExtension="rtf" type="application/rtf"/>
  <mimeType fileExtension="rtf" type="application/x-rtf"/>
  <mimeType fileExtension="rtf" type="text/richtext"/>
  <mimeType fileExtension="rtx" type="application/rtf"/>
  <mimeType fileExtension="rtx" type="text/richtext"/>
  <mimeType fileExtension="rv" type="video/vnd.rn-realvideo"/>
  <mimeType fileExtension="s" type="text/x-asm"/>
  <mimeType fileExtension="s3m" type="audio/s3m"/>
  <mimeType fileExtension="saveme" type="application/octet-stream"/>
  <mimeType fileExtension="sbk" type="application/x-tbook"/>
  <mimeType fileExtension="scm" type="application/x-lotusscreencam"/>
  <mimeType fileExtension="scm" type="text/x-script.guile"/>
  <mimeType fileExtension="scm" type="text/x-script.scheme"/>
  <mimeType fileExtension="scm" type="video/x-scm"/>
  <mimeType fileExtension="sdml" type="text/plain"/>
  <mimeType fileExtension="sdp" type="application/sdp"/>
  <mimeType fileExtension="sdp" type="application/x-sdp"/>
  <mimeType fileExtension="sdr" type="application/sounder"/>
  <mimeType fileExtension="sea" type="application/sea"/>
  <mimeType fileExtension="sea" type="application/x-sea"/>
  <mimeType fileExtension="set" type="application/set"/>
  <mimeType fileExtension="sgm" type="text/sgml"/>
  <mimeType fileExtension="sgm" type="text/x-sgml"/>
  <mimeType fileExtension="sgml" type="text/sgml"/>
  <mimeType fileExtension="sgml" type="text/x-sgml"/>
  <mimeType fileExtension="sh" type="application/x-bsh"/>
  <mimeType fileExtension="sh" type="application/x-sh"/>
  <mimeType fileExtension="sh" type="application/x-shar"/>
  <mimeType fileExtension="sh" type="text/x-script.sh"/>
  <mimeType fileExtension="shar" type="application/x-bsh"/>
  <mimeType fileExtension="shar" type="application/x-shar"/>
  <mimeType fileExtension="shtml" type="text/html"/>
  <mimeType fileExtension="shtml" type="text/x-server-parsed-html"/>
  <mimeType fileExtension="sid" type="audio/x-psid"/>
  <mimeType fileExtension="sit" type="application/x-sit"/>
  <mimeType fileExtension="sit" type="application/x-stuffit"/>
  <mimeType fileExtension="skd" type="application/x-koan"/>
  <mimeType fileExtension="skm" type="application/x-koan"/>
  <mimeType fileExtension="skp" type="application/x-koan"/>
  <mimeType fileExtension="skt" type="application/x-koan"/>
  <mimeType fileExtension="sl" type="application/x-seelogo"/>
  <mimeType fileExtension="smi" type="application/smil"/>
  <mimeType fileExtension="smil" type="application/smil"/>
  <mimeType fileExtension="snd" type="audio/basic"/>
  <mimeType fileExtension="snd" type="audio/x-adpcm"/>
  <mimeType fileExtension="sol" type="application/solids"/>
  <mimeType fileExtension="spc" type="application/x-pkcs7-certificates"/>
  <mimeType fileExtension="spc" type="text/x-speech"/>
  <mimeType fileExtension="spl" type="application/futuresplash"/>
  <mimeType fileExtension="spr" type="application/x-sprite"/>
  <mimeType fileExtension="sprite" type="application/x-sprite"/>
  <mimeType fileExtension="src" type="application/x-wais-source"/>
  <mimeType fileExtension="ssi" type="text/x-server-parsed-html"/>
  <mimeType fileExtension="ssm" type="application/streamingmedia"/>
  <mimeType fileExtension="sst" type="application/vnd.ms-pki.certstore"/>
  <mimeType fileExtension="step" type="application/step"/>
  <mimeType fileExtension="stl" type="application/sla"/>
  <mimeType fileExtension="stl" type="application/vnd.ms-pki.stl"/>
  <mimeType fileExtension="stl" type="application/x-navistyle"/>
  <mimeType fileExtension="stp" type="application/step"/>
  <mimeType fileExtension="sv4cpio" type="application/x-sv4cpio"/>
  <mimeType fileExtension="sv4crc" type="application/x-sv4crc"/>
  <mimeType fileExtension="svf" type="image/vnd.dwg"/>
  <mimeType fileExtension="svf" type="image/x-dwg"/>
  <mimeType fileExtension="svr" type="application/x-world"/>
  <mimeType fileExtension="svr" type="x-world/x-svr"/>
  <mimeType fileExtension="swf" type="application/x-shockwave-flash"/>
  <mimeType fileExtension="t" type="application/x-troff"/>
  <mimeType fileExtension="talk" type="text/x-speech"/>
  <mimeType fileExtension="tar" type="application/x-tar"/>
  <mimeType fileExtension="tbk" type="application/toolbook"/>
  <mimeType fileExtension="tbk" type="application/x-tbook"/>
  <mimeType fileExtension="tcl" type="application/x-tcl"/>
  <mimeType fileExtension="tcl" type="text/x-script.tcl"/>
  <mimeType fileExtension="tcsh" type="text/x-script.tcsh"/>
  <mimeType fileExtension="tex" type="application/x-tex"/>
  <mimeType fileExtension="texi" type="application/x-texinfo"/>
  <mimeType fileExtension="texinfo" type="application/x-texinfo"/>
  <mimeType fileExtension="text" type="application/plain"/>
  <mimeType fileExtension="text" type="text/plain"/>
  <mimeType fileExtension="tgz" type="application/gnutar"/>
  <mimeType fileExtension="tgz" type="application/x-compressed"/>
  <mimeType fileExtension="tif" type="image/tiff"/>
  <mimeType fileExtension="tif" type="image/x-tiff"/>
  <mimeType fileExtension="tiff" type="image/tiff"/>
  <mimeType fileExtension="tiff" type="image/x-tiff"/>
  <mimeType fileExtension="tr" type="application/x-troff"/>
  <mimeType fileExtension="tsi" type="audio/tsp-audio"/>
  <mimeType fileExtension="tsp" type="application/dsptype"/>
  <mimeType fileExtension="tsp" type="audio/tsplayer"/>
  <mimeType fileExtension="tsv" type="text/tab-separated-values"/>
  <mimeType fileExtension="turbot" type="image/florian"/>
  <mimeType fileExtension="txt" type="text/plain"/>
  <mimeType fileExtension="uil" type="text/x-uil"/>
  <mimeType fileExtension="uni" type="text/uri-list"/>
  <mimeType fileExtension="unis" type="text/uri-list"/>
  <mimeType fileExtension="unv" type="application/i-deas"/>
  <mimeType fileExtension="uri" type="text/uri-list"/>
  <mimeType fileExtension="uris" type="text/uri-list"/>
  <mimeType fileExtension="ustar" type="application/x-ustar"/>
  <mimeType fileExtension="ustar" type="multipart/x-ustar"/>
  <mimeType fileExtension="uu" type="application/octet-stream"/>
  <mimeType fileExtension="uu" type="text/x-uuencode"/>
  <mimeType fileExtension="uue" type="text/x-uuencode"/>
  <mimeType fileExtension="vcd" type="application/x-cdlink"/>
  <mimeType fileExtension="vcs" type="text/x-vcalendar"/>
  <mimeType fileExtension="vda" type="application/vda"/>
  <mimeType fileExtension="vdo" type="video/vdo"/>
  <mimeType fileExtension="vew" type="application/groupwise"/>
  <mimeType fileExtension="viv" type="video/vivo"/>
  <mimeType fileExtension="viv" type="video/vnd.vivo"/>
  <mimeType fileExtension="vivo" type="video/vivo"/>
  <mimeType fileExtension="vivo" type="video/vnd.vivo"/>
  <mimeType fileExtension="vmd" type="application/vocaltec-media-desc"/>
  <mimeType fileExtension="vmf" type="application/vocaltec-media-file"/>
  <mimeType fileExtension="voc" type="audio/voc"/>
  <mimeType fileExtension="voc" type="audio/x-voc"/>
  <mimeType fileExtension="vos" type="video/vosaic"/>
  <mimeType fileExtension="vox" type="audio/voxware"/>
  <mimeType fileExtension="vqe" type="audio/x-twinvq-plugin"/>
  <mimeType fileExtension="vqf" type="audio/x-twinvq"/>
  <mimeType fileExtension="vql" type="audio/x-twinvq-plugin"/>
  <mimeType fileExtension="vrml" type="application/x-vrml"/>
  <mimeType fileExtension="vrml" type="model/vrml"/>
  <mimeType fileExtension="vrml" type="x-world/x-vrml"/>
  <mimeType fileExtension="vrt" type="x-world/x-vrt"/>
  <mimeType fileExtension="vsd" type="application/x-visio"/>
  <mimeType fileExtension="vst" type="application/x-visio"/>
  <mimeType fileExtension="vsw" type="application/x-visio"/>
  <mimeType fileExtension="w60" type="application/wordperfect6.0"/>
  <mimeType fileExtension="w61" type="application/wordperfect6.1"/>
  <mimeType fileExtension="w6w" type="application/msword"/>
  <mimeType fileExtension="wav" type="audio/wav"/>
  <mimeType fileExtension="wav" type="audio/x-wav"/>
  <mimeType fileExtension="wb1" type="application/x-qpro"/>
  <mimeType fileExtension="wbmp" type="image/vnd.wap.wbmp"/>
  <mimeType fileExtension="web" type="application/vnd.xara"/>
  <mimeType fileExtension="wiz" type="application/msword"/>
  <mimeType fileExtension="wk1" type="application/x-123"/>
  <mimeType fileExtension="wmf" type="windows/metafile"/>
  <mimeType fileExtension="wml" type="text/vnd.wap.wml"/>
  <mimeType fileExtension="wmlc" type="application/vnd.wap.wmlc"/>
  <mimeType fileExtension="wmls" type="text/vnd.wap.wmlscript"/>
  <mimeType fileExtension="wmlsc" type="application/vnd.wap.wmlscriptc"/>
  <mimeType fileExtension="word" type="application/msword"/>
  <mimeType fileExtension="wp" type="application/wordperfect"/>
  <mimeType fileExtension="wp5" type="application/wordperfect"/>
  <mimeType fileExtension="wp5" type="application/wordperfect6.0"/>
  <mimeType fileExtension="wp6" type="application/wordperfect"/>
  <mimeType fileExtension="wpd" type="application/wordperfect"/>
  <mimeType fileExtension="wpd" type="application/x-wpwin"/>
  <mimeType fileExtension="wq1" type="application/x-lotus"/>
  <mimeType fileExtension="wri" type="application/mswrite"/>
  <mimeType fileExtension="wri" type="application/x-wri"/>
  <mimeType fileExtension="wrl" type="application/x-world"/>
  <mimeType fileExtension="wrl" type="model/vrml"/>
  <mimeType fileExtension="wrl" type="x-world/x-vrml"/>
  <mimeType fileExtension="wrz" type="model/vrml"/>
  <mimeType fileExtension="wrz" type="x-world/x-vrml"/>
  <mimeType fileExtension="wsc" type="text/scriplet"/>
  <mimeType fileExtension="wsrc" type="application/x-wais-source"/>
  <mimeType fileExtension="wtk" type="application/x-wintalk"/>
  <mimeType fileExtension="xbm" type="image/x-xbitmap"/>
  <mimeType fileExtension="xbm" type="image/x-xbm"/>
  <mimeType fileExtension="xbm" type="image/xbm"/>
  <mimeType fileExtension="xdr" type="video/x-amt-demorun"/>
  <mimeType fileExtension="xgz" type="xgl/drawing"/>
  <mimeType fileExtension="xif" type="image/vnd.xiff"/>
  <mimeType fileExtension="xl" type="application/excel"/>
  <mimeType fileExtension="xla" type="application/excel"/>
  <mimeType fileExtension="xla" type="application/x-excel"/>
  <mimeType fileExtension="xla" type="application/x-msexcel"/>
  <mimeType fileExtension="xlb" type="application/excel"/>
  <mimeType fileExtension="xlb" type="application/vnd.ms-excel"/>
  <mimeType fileExtension="xlb" type="application/x-excel"/>
  <mimeType fileExtension="xlc" type="application/excel"/>
  <mimeType fileExtension="xlc" type="application/vnd.ms-excel"/>
  <mimeType fileExtension="xlc" type="application/x-excel"/>
  <mimeType fileExtension="xld" type="application/excel"/>
  <mimeType fileExtension="xld" type="application/x-excel"/>
  <mimeType fileExtension="xlk" type="application/excel"/>
  <mimeType fileExtension="xlk" type="application/x-excel"/>
  <mimeType fileExtension="xll" type="application/excel"/>
  <mimeType fileExtension="xll" type="application/vnd.ms-excel"/>
  <mimeType fileExtension="xll" type="application/x-excel"/>
  <mimeType fileExtension="xlm" type="application/excel"/>
  <mimeType fileExtension="xlm" type="application/vnd.ms-excel"/>
  <mimeType fileExtension="xlm" type="application/x-excel"/>
  <mimeType fileExtension="xls" type="application/excel"/>
  <mimeType fileExtension="xls" type="application/vnd.ms-excel"/>
  <mimeType fileExtension="xls" type="application/x-excel"/>
  <mimeType fileExtension="xls" type="application/x-msexcel"/>
  <mimeType fileExtension="xlt" type="application/excel"/>
  <mimeType fileExtension="xlt" type="application/x-excel"/>
  <mimeType fileExtension="xlv" type="application/excel"/>
  <mimeType fileExtension="xlv" type="application/x-excel"/>
  <mimeType fileExtension="xlw" type="application/excel"/>
  <mimeType fileExtension="xlw" type="application/vnd.ms-excel"/>
  <mimeType fileExtension="xlw" type="application/x-excel"/>
  <mimeType fileExtension="xlw" type="application/x-msexcel"/>
  <mimeType fileExtension="xm" type="audio/xm"/>
  <mimeType fileExtension="xml" type="application/xml"/>
  <mimeType fileExtension="xml" type="text/xml"/>
  <mimeType fileExtension="xmz" type="xgl/movie"/>
  <mimeType fileExtension="xpix" type="application/x-vnd.ls-xpix"/>
  <mimeType fileExtension="xpm" type="image/x-xpixmap"/>
  <mimeType fileExtension="xpm" type="image/xpm"/>
  <mimeType fileExtension="x-png" type="image/png"/>
  <mimeType fileExtension="xsr" type="video/x-amt-showrun"/>
  <mimeType fileExtension="xwd" type="image/x-xwd"/>
  <mimeType fileExtension="xwd" type="image/x-xwindowdump"/>
  <mimeType fileExtension="xyz" type="chemical/x-pdb"/>
  <mimeType fileExtension="z" type="application/x-compress"/>
  <mimeType fileExtension="z" type="application/x-compressed"/>
  <mimeType fileExtension="zip" type="application/x-compressed"/>
  <mimeType fileExtension="zip" type="application/x-zip-compressed"/>
  <mimeType fileExtension="zip" type="application/zip"/>
  <mimeType fileExtension="zip" type="multipart/x-zip"/>
  <mimeType fileExtension="zoo" type="application/octet-stream"/>
  <mimeType fileExtension="zsh" type="text/x-script.zsh"/>
</mimeTypes>;
   }
}
