package com.ankamagames.dofus.network
{
    import flash.utils.Dictionary;
    import com.ankamagames.dofus.network.types.game.character.CharacterMinimalPlusLookInformations;
    import com.ankamagames.dofus.network.types.game.character.choice.CharacterBaseInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.party.PartyMemberInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.party.PartyMemberArenaInformations;
    import com.ankamagames.dofus.network.types.game.character.choice.CharacterHardcoreInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.party.PartyInvitationMemberInformations;
    import com.ankamagames.dofus.network.types.game.character.CharacterMinimalGuildInformations;
    import com.ankamagames.dofus.network.types.game.character.CharacterMinimalAllianceInformations;
    import com.ankamagames.dofus.network.types.game.character.CharacterMinimalPlusLookAndGradeInformations;
    import com.ankamagames.dofus.network.types.game.context.EntityDispositionInformations;
    import com.ankamagames.dofus.network.types.game.context.IdentifiedEntityDispositionInformations;
    import com.ankamagames.dofus.network.types.game.context.FightEntityDispositionInformations;
    import com.ankamagames.dofus.network.types.game.social.AbstractSocialGroupInfos;
    import com.ankamagames.dofus.network.types.game.context.roleplay.BasicAllianceInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.BasicNamedAllianceInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.AllianceInformations;
    import com.ankamagames.dofus.network.types.game.social.AllianceFactSheetInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.BasicGuildInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GuildInformations;
    import com.ankamagames.dofus.network.types.game.social.GuildFactSheetInformations;
    import com.ankamagames.dofus.network.types.game.social.GuildInsiderFactSheetInformations;
    import com.ankamagames.dofus.network.types.game.social.AlliancedGuildFactSheetInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GuildInAllianceInformations;
    import com.ankamagames.dofus.network.types.game.social.GuildVersatileInformations;
    import com.ankamagames.dofus.network.types.game.social.GuildInAllianceVersatileInformations;
    import com.ankamagames.dofus.network.types.game.prism.PrismSubareaEmptyInfo;
    import com.ankamagames.dofus.network.types.game.prism.PrismGeolocalizedInformation;
    import com.ankamagames.dofus.network.types.game.prism.PrismInformation;
    import com.ankamagames.dofus.network.types.game.prism.AllianceInsiderPrismInformation;
    import com.ankamagames.dofus.network.types.game.prism.AlliancePrismInformation;
    import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberCharacterInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberWithAllianceCharacterInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberCompanionInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberMonsterInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberTaxCollectorInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.FightTeamInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.FightAllianceTeamInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightMinimalStats;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightMinimalStatsPreparation;
    import com.ankamagames.dofus.network.types.game.context.fight.FightResultListEntry;
    import com.ankamagames.dofus.network.types.game.context.fight.FightResultFighterListEntry;
    import com.ankamagames.dofus.network.types.game.context.fight.FightResultMutantListEntry;
    import com.ankamagames.dofus.network.types.game.context.fight.FightResultPlayerListEntry;
    import com.ankamagames.dofus.network.types.game.context.fight.FightResultTaxCollectorListEntry;
    import com.ankamagames.dofus.network.types.game.context.fight.FightResultAdditionalData;
    import com.ankamagames.dofus.network.types.game.context.fight.FightResultPvpData;
    import com.ankamagames.dofus.network.types.game.context.fight.FightResultExperienceData;
    import com.ankamagames.dofus.network.types.game.actions.fight.AbstractFightDispellableEffect;
    import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporaryBoostEffect;
    import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporaryBoostStateEffect;
    import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporaryBoostWeaponDamagesEffect;
    import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporarySpellBoostEffect;
    import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporarySpellImmunityEffect;
    import com.ankamagames.dofus.network.types.game.actions.fight.FightTriggeredEffect;
    import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffect;
    import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectInteger;
    import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectCreature;
    import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectLadder;
    import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectDuration;
    import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectDice;
    import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectMinMax;
    import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectString;
    import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectMount;
    import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectDate;
    import com.ankamagames.dofus.network.types.game.mount.UpdateMountBoost;
    import com.ankamagames.dofus.network.types.game.mount.UpdateMountIntBoost;
    import com.ankamagames.dofus.network.types.game.shortcut.Shortcut;
    import com.ankamagames.dofus.network.types.game.shortcut.ShortcutObject;
    import com.ankamagames.dofus.network.types.game.shortcut.ShortcutObjectItem;
    import com.ankamagames.dofus.network.types.game.shortcut.ShortcutObjectPreset;
    import com.ankamagames.dofus.network.types.game.shortcut.ShortcutSpell;
    import com.ankamagames.dofus.network.types.game.shortcut.ShortcutEmote;
    import com.ankamagames.dofus.network.types.game.shortcut.ShortcutSmiley;
    import com.ankamagames.dofus.network.types.game.friend.IgnoredInformations;
    import com.ankamagames.dofus.network.types.game.friend.IgnoredOnlineInformations;
    import com.ankamagames.dofus.network.types.game.friend.FriendInformations;
    import com.ankamagames.dofus.network.types.game.friend.FriendOnlineInformations;
    import com.ankamagames.dofus.network.types.game.friend.FriendSpouseInformations;
    import com.ankamagames.dofus.network.types.game.friend.FriendSpouseOnlineInformations;
    import com.ankamagames.dofus.network.types.game.interactive.InteractiveElementSkill;
    import com.ankamagames.dofus.network.types.game.interactive.InteractiveElementNamedSkill;
    import com.ankamagames.dofus.network.types.game.interactive.InteractiveElement;
    import com.ankamagames.dofus.network.types.game.interactive.InteractiveElementWithAgeBonus;
    import com.ankamagames.dofus.network.types.game.interactive.skill.SkillActionDescription;
    import com.ankamagames.dofus.network.types.game.interactive.skill.SkillActionDescriptionTimed;
    import com.ankamagames.dofus.network.types.game.interactive.skill.SkillActionDescriptionCollect;
    import com.ankamagames.dofus.network.types.game.interactive.skill.SkillActionDescriptionCraft;
    import com.ankamagames.dofus.network.types.game.house.HouseInformations;
    import com.ankamagames.dofus.network.types.game.house.HouseInformationsExtended;
    import com.ankamagames.dofus.network.types.game.paddock.PaddockInformations;
    import com.ankamagames.dofus.network.types.game.paddock.PaddockBuyableInformations;
    import com.ankamagames.dofus.network.types.game.paddock.PaddockAbandonnedInformations;
    import com.ankamagames.dofus.network.types.game.paddock.PaddockPrivateInformations;
    import com.ankamagames.dofus.network.types.game.paddock.PaddockContentInformations;
    import com.ankamagames.dofus.network.types.game.context.GameContextActorInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightAIInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightMonsterInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightMonsterWithAlignmentInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightTaxCollectorInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterNamedInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightMutantInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightCharacterInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightCompanionInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayActorInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayNamedActorInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayHumanoidInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayMutantInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayCharacterInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayMerchantInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayMountInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayNpcInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayNpcWithQuestInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayGroupMonsterInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayGroupMonsterWaveInformations;
    import com.ankamagames.dofus.network.types.game.context.GameRolePlayTaxCollectorInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayPrismInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayPortalInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.HumanInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOption;
    import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionAlliance;
    import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionOrnament;
    import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionFollowers;
    import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionObjectUse;
    import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionGuild;
    import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionTitle;
    import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionEmote;
    import com.ankamagames.dofus.network.types.game.context.TaxCollectorStaticInformations;
    import com.ankamagames.dofus.network.types.game.context.TaxCollectorStaticExtendedInformations;
    import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorInformations;
    import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorComplementaryInformations;
    import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorLootInformations;
    import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorWaitingForHelpInformations;
    import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorGuildInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GroupMonsterStaticInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.GroupMonsterStaticInformationsWithAlternatives;
    import com.ankamagames.dofus.network.types.game.context.roleplay.quest.QuestActiveInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.quest.QuestActiveDetailedInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.quest.QuestObjectiveInformations;
    import com.ankamagames.dofus.network.types.game.context.roleplay.quest.QuestObjectiveInformationsWithCompletion;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterLightInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterNamedLightInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterMonsterLightInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterCompanionLightInformations;
    import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterTaxCollectorLightInformations;
    import com.ankamagames.dofus.network.types.game.context.MapCoordinates;
    import com.ankamagames.dofus.network.types.game.context.MapCoordinatesAndId;
    import com.ankamagames.dofus.network.types.game.context.MapCoordinatesExtended;
    import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStep;
    import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepFight;
    import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepFollowDirection;
    import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepDig;
    import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepFollowDirectionToPOI;
    import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.PortalInformation;
    import com.ankamagames.dofus.network.types.game.character.status.PlayerStatus;
    import com.ankamagames.dofus.network.types.game.character.status.PlayerStatusExtended;
    import com.ankamagames.dofus.network.types.game.approach.ServerSessionConstant;
    import com.ankamagames.dofus.network.types.game.approach.ServerSessionConstantString;
    import com.ankamagames.dofus.network.types.game.approach.ServerSessionConstantInteger;
    import com.ankamagames.dofus.network.types.game.approach.ServerSessionConstantLong;
    import com.ankamagames.jerakine.managers.StoreDataManager;

    public class ProtocolTypeManager 
    {

        private static const _typesTypes:Dictionary = new Dictionary();

        {
            _typesTypes[163] = CharacterMinimalPlusLookInformations;
            _typesTypes[45] = CharacterBaseInformations;
            _typesTypes[90] = PartyMemberInformations;
            _typesTypes[391] = PartyMemberArenaInformations;
            _typesTypes[86] = CharacterHardcoreInformations;
            _typesTypes[376] = PartyInvitationMemberInformations;
            _typesTypes[445] = CharacterMinimalGuildInformations;
            _typesTypes[444] = CharacterMinimalAllianceInformations;
            _typesTypes[193] = CharacterMinimalPlusLookAndGradeInformations;
            _typesTypes[45] = CharacterBaseInformations;
            _typesTypes[90] = PartyMemberInformations;
            _typesTypes[391] = PartyMemberArenaInformations;
            _typesTypes[86] = CharacterHardcoreInformations;
            _typesTypes[376] = PartyInvitationMemberInformations;
            _typesTypes[60] = EntityDispositionInformations;
            _typesTypes[107] = IdentifiedEntityDispositionInformations;
            _typesTypes[217] = FightEntityDispositionInformations;
            _typesTypes[416] = AbstractSocialGroupInfos;
            _typesTypes[419] = BasicAllianceInformations;
            _typesTypes[418] = BasicNamedAllianceInformations;
            _typesTypes[417] = AllianceInformations;
            _typesTypes[421] = AllianceFactSheetInformations;
            _typesTypes[365] = BasicGuildInformations;
            _typesTypes[127] = GuildInformations;
            _typesTypes[424] = GuildFactSheetInformations;
            _typesTypes[423] = GuildInsiderFactSheetInformations;
            _typesTypes[422] = AlliancedGuildFactSheetInformations;
            _typesTypes[420] = GuildInAllianceInformations;
            _typesTypes[435] = GuildVersatileInformations;
            _typesTypes[437] = GuildInAllianceVersatileInformations;
            _typesTypes[424] = GuildFactSheetInformations;
            _typesTypes[423] = GuildInsiderFactSheetInformations;
            _typesTypes[421] = AllianceFactSheetInformations;
            _typesTypes[438] = PrismSubareaEmptyInfo;
            _typesTypes[434] = PrismGeolocalizedInformation;
            _typesTypes[428] = PrismInformation;
            _typesTypes[431] = AllianceInsiderPrismInformation;
            _typesTypes[427] = AlliancePrismInformation;
            _typesTypes[44] = FightTeamMemberInformations;
            _typesTypes[13] = FightTeamMemberCharacterInformations;
            _typesTypes[426] = FightTeamMemberWithAllianceCharacterInformations;
            _typesTypes[451] = FightTeamMemberCompanionInformations;
            _typesTypes[6] = FightTeamMemberMonsterInformations;
            _typesTypes[177] = FightTeamMemberTaxCollectorInformations;
            _typesTypes[33] = FightTeamInformations;
            _typesTypes[439] = FightAllianceTeamInformations;
            _typesTypes[31] = GameFightMinimalStats;
            _typesTypes[360] = GameFightMinimalStatsPreparation;
            _typesTypes[16] = FightResultListEntry;
            _typesTypes[189] = FightResultFighterListEntry;
            _typesTypes[216] = FightResultMutantListEntry;
            _typesTypes[24] = FightResultPlayerListEntry;
            _typesTypes[84] = FightResultTaxCollectorListEntry;
            _typesTypes[191] = FightResultAdditionalData;
            _typesTypes[190] = FightResultPvpData;
            _typesTypes[192] = FightResultExperienceData;
            _typesTypes[206] = AbstractFightDispellableEffect;
            _typesTypes[209] = FightTemporaryBoostEffect;
            _typesTypes[214] = FightTemporaryBoostStateEffect;
            _typesTypes[211] = FightTemporaryBoostWeaponDamagesEffect;
            _typesTypes[207] = FightTemporarySpellBoostEffect;
            _typesTypes[366] = FightTemporarySpellImmunityEffect;
            _typesTypes[210] = FightTriggeredEffect;
            _typesTypes[76] = ObjectEffect;
            _typesTypes[70] = ObjectEffectInteger;
            _typesTypes[71] = ObjectEffectCreature;
            _typesTypes[81] = ObjectEffectLadder;
            _typesTypes[75] = ObjectEffectDuration;
            _typesTypes[73] = ObjectEffectDice;
            _typesTypes[82] = ObjectEffectMinMax;
            _typesTypes[74] = ObjectEffectString;
            _typesTypes[179] = ObjectEffectMount;
            _typesTypes[72] = ObjectEffectDate;
            _typesTypes[356] = UpdateMountBoost;
            _typesTypes[357] = UpdateMountIntBoost;
            _typesTypes[369] = Shortcut;
            _typesTypes[367] = ShortcutObject;
            _typesTypes[371] = ShortcutObjectItem;
            _typesTypes[370] = ShortcutObjectPreset;
            _typesTypes[368] = ShortcutSpell;
            _typesTypes[389] = ShortcutEmote;
            _typesTypes[388] = ShortcutSmiley;
            _typesTypes[106] = IgnoredInformations;
            _typesTypes[105] = IgnoredOnlineInformations;
            _typesTypes[78] = FriendInformations;
            _typesTypes[92] = FriendOnlineInformations;
            _typesTypes[77] = FriendSpouseInformations;
            _typesTypes[93] = FriendSpouseOnlineInformations;
            _typesTypes[219] = InteractiveElementSkill;
            _typesTypes[220] = InteractiveElementNamedSkill;
            _typesTypes[80] = InteractiveElement;
            _typesTypes[398] = InteractiveElementWithAgeBonus;
            _typesTypes[90] = PartyMemberInformations;
            _typesTypes[391] = PartyMemberArenaInformations;
            _typesTypes[102] = SkillActionDescription;
            _typesTypes[103] = SkillActionDescriptionTimed;
            _typesTypes[99] = SkillActionDescriptionCollect;
            _typesTypes[100] = SkillActionDescriptionCraft;
            _typesTypes[111] = HouseInformations;
            _typesTypes[112] = HouseInformationsExtended;
            _typesTypes[132] = PaddockInformations;
            _typesTypes[130] = PaddockBuyableInformations;
            _typesTypes[133] = PaddockAbandonnedInformations;
            _typesTypes[131] = PaddockPrivateInformations;
            _typesTypes[183] = PaddockContentInformations;
            _typesTypes[150] = GameContextActorInformations;
            _typesTypes[143] = GameFightFighterInformations;
            _typesTypes[151] = GameFightAIInformations;
            _typesTypes[29] = GameFightMonsterInformations;
            _typesTypes[203] = GameFightMonsterWithAlignmentInformations;
            _typesTypes[48] = GameFightTaxCollectorInformations;
            _typesTypes[158] = GameFightFighterNamedInformations;
            _typesTypes[50] = GameFightMutantInformations;
            _typesTypes[46] = GameFightCharacterInformations;
            _typesTypes[450] = GameFightCompanionInformations;
            _typesTypes[141] = GameRolePlayActorInformations;
            _typesTypes[154] = GameRolePlayNamedActorInformations;
            _typesTypes[159] = GameRolePlayHumanoidInformations;
            _typesTypes[3] = GameRolePlayMutantInformations;
            _typesTypes[36] = GameRolePlayCharacterInformations;
            _typesTypes[129] = GameRolePlayMerchantInformations;
            _typesTypes[180] = GameRolePlayMountInformations;
            _typesTypes[156] = GameRolePlayNpcInformations;
            _typesTypes[383] = GameRolePlayNpcWithQuestInformations;
            _typesTypes[160] = GameRolePlayGroupMonsterInformations;
            _typesTypes[464] = GameRolePlayGroupMonsterWaveInformations;
            _typesTypes[148] = GameRolePlayTaxCollectorInformations;
            _typesTypes[161] = GameRolePlayPrismInformations;
            _typesTypes[467] = GameRolePlayPortalInformations;
            _typesTypes[141] = GameRolePlayActorInformations;
            _typesTypes[154] = GameRolePlayNamedActorInformations;
            _typesTypes[159] = GameRolePlayHumanoidInformations;
            _typesTypes[3] = GameRolePlayMutantInformations;
            _typesTypes[36] = GameRolePlayCharacterInformations;
            _typesTypes[129] = GameRolePlayMerchantInformations;
            _typesTypes[180] = GameRolePlayMountInformations;
            _typesTypes[156] = GameRolePlayNpcInformations;
            _typesTypes[383] = GameRolePlayNpcWithQuestInformations;
            _typesTypes[160] = GameRolePlayGroupMonsterInformations;
            _typesTypes[464] = GameRolePlayGroupMonsterWaveInformations;
            _typesTypes[148] = GameRolePlayTaxCollectorInformations;
            _typesTypes[161] = GameRolePlayPrismInformations;
            _typesTypes[467] = GameRolePlayPortalInformations;
            _typesTypes[157] = HumanInformations;
            _typesTypes[406] = HumanOption;
            _typesTypes[425] = HumanOptionAlliance;
            _typesTypes[411] = HumanOptionOrnament;
            _typesTypes[410] = HumanOptionFollowers;
            _typesTypes[449] = HumanOptionObjectUse;
            _typesTypes[409] = HumanOptionGuild;
            _typesTypes[408] = HumanOptionTitle;
            _typesTypes[407] = HumanOptionEmote;
            _typesTypes[147] = TaxCollectorStaticInformations;
            _typesTypes[440] = TaxCollectorStaticExtendedInformations;
            _typesTypes[167] = TaxCollectorInformations;
            _typesTypes[448] = TaxCollectorComplementaryInformations;
            _typesTypes[372] = TaxCollectorLootInformations;
            _typesTypes[447] = TaxCollectorWaitingForHelpInformations;
            _typesTypes[446] = TaxCollectorGuildInformations;
            _typesTypes[140] = GroupMonsterStaticInformations;
            _typesTypes[396] = GroupMonsterStaticInformationsWithAlternatives;
            _typesTypes[381] = QuestActiveInformations;
            _typesTypes[382] = QuestActiveDetailedInformations;
            _typesTypes[385] = QuestObjectiveInformations;
            _typesTypes[386] = QuestObjectiveInformationsWithCompletion;
            _typesTypes[143] = GameFightFighterInformations;
            _typesTypes[151] = GameFightAIInformations;
            _typesTypes[29] = GameFightMonsterInformations;
            _typesTypes[203] = GameFightMonsterWithAlignmentInformations;
            _typesTypes[48] = GameFightTaxCollectorInformations;
            _typesTypes[158] = GameFightFighterNamedInformations;
            _typesTypes[50] = GameFightMutantInformations;
            _typesTypes[46] = GameFightCharacterInformations;
            _typesTypes[450] = GameFightCompanionInformations;
            _typesTypes[413] = GameFightFighterLightInformations;
            _typesTypes[456] = GameFightFighterNamedLightInformations;
            _typesTypes[455] = GameFightFighterMonsterLightInformations;
            _typesTypes[454] = GameFightFighterCompanionLightInformations;
            _typesTypes[457] = GameFightFighterTaxCollectorLightInformations;
            _typesTypes[174] = MapCoordinates;
            _typesTypes[392] = MapCoordinatesAndId;
            _typesTypes[176] = MapCoordinatesExtended;
            _typesTypes[463] = TreasureHuntStep;
            _typesTypes[462] = TreasureHuntStepFight;
            _typesTypes[468] = TreasureHuntStepFollowDirection;
            _typesTypes[465] = TreasureHuntStepDig;
            _typesTypes[461] = TreasureHuntStepFollowDirectionToPOI;
            _typesTypes[466] = PortalInformation;
            _typesTypes[415] = PlayerStatus;
            _typesTypes[414] = PlayerStatusExtended;
            _typesTypes[430] = ServerSessionConstant;
            _typesTypes[436] = ServerSessionConstantString;
            _typesTypes[433] = ServerSessionConstantInteger;
            _typesTypes[429] = ServerSessionConstantLong;
        }


        public static function getInstance(base:Class, typeId:uint)
        {
            var objType:Class = _typesTypes[typeId];
            if (!(objType))
            {
                throw (new Error((("Type with id " + typeId) + " is unknown.")));
            };
            var obj:* = new (objType)();
            if (!((obj is base)))
            {
                throw (new Error((((("Type " + typeId) + " is not a ") + base) + ".")));
            };
            return (obj);
        }

        public static function register():void
        {
            StoreDataManager.getInstance().registerClass(new CharacterMinimalPlusLookInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new CharacterBaseInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new PartyMemberInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new PartyMemberArenaInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new CharacterHardcoreInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new PartyInvitationMemberInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new CharacterMinimalGuildInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new CharacterMinimalAllianceInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new CharacterMinimalPlusLookAndGradeInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new CharacterBaseInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new PartyMemberInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new PartyMemberArenaInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new CharacterHardcoreInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new PartyInvitationMemberInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new EntityDispositionInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new IdentifiedEntityDispositionInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new FightEntityDispositionInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new AbstractSocialGroupInfos(), true, true);
            StoreDataManager.getInstance().registerClass(new BasicAllianceInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new BasicNamedAllianceInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new AllianceInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new AllianceFactSheetInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new BasicGuildInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GuildInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GuildFactSheetInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GuildInsiderFactSheetInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new AlliancedGuildFactSheetInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GuildInAllianceInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GuildVersatileInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GuildInAllianceVersatileInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GuildFactSheetInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GuildInsiderFactSheetInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new AllianceFactSheetInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new PrismSubareaEmptyInfo(), true, true);
            StoreDataManager.getInstance().registerClass(new PrismGeolocalizedInformation(), true, true);
            StoreDataManager.getInstance().registerClass(new PrismInformation(), true, true);
            StoreDataManager.getInstance().registerClass(new AllianceInsiderPrismInformation(), true, true);
            StoreDataManager.getInstance().registerClass(new AlliancePrismInformation(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTeamMemberInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTeamMemberCharacterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTeamMemberWithAllianceCharacterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTeamMemberCompanionInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTeamMemberMonsterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTeamMemberTaxCollectorInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTeamInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new FightAllianceTeamInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightMinimalStats(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightMinimalStatsPreparation(), true, true);
            StoreDataManager.getInstance().registerClass(new FightResultListEntry(), true, true);
            StoreDataManager.getInstance().registerClass(new FightResultFighterListEntry(), true, true);
            StoreDataManager.getInstance().registerClass(new FightResultMutantListEntry(), true, true);
            StoreDataManager.getInstance().registerClass(new FightResultPlayerListEntry(), true, true);
            StoreDataManager.getInstance().registerClass(new FightResultTaxCollectorListEntry(), true, true);
            StoreDataManager.getInstance().registerClass(new FightResultAdditionalData(), true, true);
            StoreDataManager.getInstance().registerClass(new FightResultPvpData(), true, true);
            StoreDataManager.getInstance().registerClass(new FightResultExperienceData(), true, true);
            StoreDataManager.getInstance().registerClass(new AbstractFightDispellableEffect(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTemporaryBoostEffect(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTemporaryBoostStateEffect(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTemporaryBoostWeaponDamagesEffect(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTemporarySpellBoostEffect(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTemporarySpellImmunityEffect(), true, true);
            StoreDataManager.getInstance().registerClass(new FightTriggeredEffect(), true, true);
            StoreDataManager.getInstance().registerClass(new ObjectEffect(), true, true);
            StoreDataManager.getInstance().registerClass(new ObjectEffectInteger(), true, true);
            StoreDataManager.getInstance().registerClass(new ObjectEffectCreature(), true, true);
            StoreDataManager.getInstance().registerClass(new ObjectEffectLadder(), true, true);
            StoreDataManager.getInstance().registerClass(new ObjectEffectDuration(), true, true);
            StoreDataManager.getInstance().registerClass(new ObjectEffectDice(), true, true);
            StoreDataManager.getInstance().registerClass(new ObjectEffectMinMax(), true, true);
            StoreDataManager.getInstance().registerClass(new ObjectEffectString(), true, true);
            StoreDataManager.getInstance().registerClass(new ObjectEffectMount(), true, true);
            StoreDataManager.getInstance().registerClass(new ObjectEffectDate(), true, true);
            StoreDataManager.getInstance().registerClass(new UpdateMountBoost(), true, true);
            StoreDataManager.getInstance().registerClass(new UpdateMountIntBoost(), true, true);
            StoreDataManager.getInstance().registerClass(new Shortcut(), true, true);
            StoreDataManager.getInstance().registerClass(new ShortcutObject(), true, true);
            StoreDataManager.getInstance().registerClass(new ShortcutObjectItem(), true, true);
            StoreDataManager.getInstance().registerClass(new ShortcutObjectPreset(), true, true);
            StoreDataManager.getInstance().registerClass(new ShortcutSpell(), true, true);
            StoreDataManager.getInstance().registerClass(new ShortcutEmote(), true, true);
            StoreDataManager.getInstance().registerClass(new ShortcutSmiley(), true, true);
            StoreDataManager.getInstance().registerClass(new IgnoredInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new IgnoredOnlineInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new FriendInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new FriendOnlineInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new FriendSpouseInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new FriendSpouseOnlineInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new InteractiveElementSkill(), true, true);
            StoreDataManager.getInstance().registerClass(new InteractiveElementNamedSkill(), true, true);
            StoreDataManager.getInstance().registerClass(new InteractiveElement(), true, true);
            StoreDataManager.getInstance().registerClass(new InteractiveElementWithAgeBonus(), true, true);
            StoreDataManager.getInstance().registerClass(new PartyMemberInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new PartyMemberArenaInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new SkillActionDescription(), true, true);
            StoreDataManager.getInstance().registerClass(new SkillActionDescriptionTimed(), true, true);
            StoreDataManager.getInstance().registerClass(new SkillActionDescriptionCollect(), true, true);
            StoreDataManager.getInstance().registerClass(new SkillActionDescriptionCraft(), true, true);
            StoreDataManager.getInstance().registerClass(new HouseInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new HouseInformationsExtended(), true, true);
            StoreDataManager.getInstance().registerClass(new PaddockInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new PaddockBuyableInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new PaddockAbandonnedInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new PaddockPrivateInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new PaddockContentInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameContextActorInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightFighterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightAIInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightMonsterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightMonsterWithAlignmentInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightTaxCollectorInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightFighterNamedInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightMutantInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightCharacterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightCompanionInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayActorInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayNamedActorInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayHumanoidInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayMutantInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayCharacterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayMerchantInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayMountInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayNpcInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayNpcWithQuestInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterWaveInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayTaxCollectorInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayPrismInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayPortalInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayActorInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayNamedActorInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayHumanoidInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayMutantInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayCharacterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayMerchantInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayMountInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayNpcInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayNpcWithQuestInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterWaveInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayTaxCollectorInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayPrismInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameRolePlayPortalInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new HumanInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new HumanOption(), true, true);
            StoreDataManager.getInstance().registerClass(new HumanOptionAlliance(), true, true);
            StoreDataManager.getInstance().registerClass(new HumanOptionOrnament(), true, true);
            StoreDataManager.getInstance().registerClass(new HumanOptionFollowers(), true, true);
            StoreDataManager.getInstance().registerClass(new HumanOptionObjectUse(), true, true);
            StoreDataManager.getInstance().registerClass(new HumanOptionGuild(), true, true);
            StoreDataManager.getInstance().registerClass(new HumanOptionTitle(), true, true);
            StoreDataManager.getInstance().registerClass(new HumanOptionEmote(), true, true);
            StoreDataManager.getInstance().registerClass(new TaxCollectorStaticInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new TaxCollectorStaticExtendedInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new TaxCollectorInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new TaxCollectorComplementaryInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new TaxCollectorLootInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new TaxCollectorWaitingForHelpInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new TaxCollectorGuildInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GroupMonsterStaticInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GroupMonsterStaticInformationsWithAlternatives(), true, true);
            StoreDataManager.getInstance().registerClass(new QuestActiveInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new QuestActiveDetailedInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new QuestObjectiveInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new QuestObjectiveInformationsWithCompletion(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightFighterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightAIInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightMonsterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightMonsterWithAlignmentInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightTaxCollectorInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightFighterNamedInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightMutantInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightCharacterInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightCompanionInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightFighterLightInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightFighterNamedLightInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightFighterMonsterLightInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightFighterCompanionLightInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new GameFightFighterTaxCollectorLightInformations(), true, true);
            StoreDataManager.getInstance().registerClass(new MapCoordinates(), true, true);
            StoreDataManager.getInstance().registerClass(new MapCoordinatesAndId(), true, true);
            StoreDataManager.getInstance().registerClass(new MapCoordinatesExtended(), true, true);
            StoreDataManager.getInstance().registerClass(new TreasureHuntStep(), true, true);
            StoreDataManager.getInstance().registerClass(new TreasureHuntStepFight(), true, true);
            StoreDataManager.getInstance().registerClass(new TreasureHuntStepFollowDirection(), true, true);
            StoreDataManager.getInstance().registerClass(new TreasureHuntStepDig(), true, true);
            StoreDataManager.getInstance().registerClass(new TreasureHuntStepFollowDirectionToPOI(), true, true);
            StoreDataManager.getInstance().registerClass(new PortalInformation(), true, true);
            StoreDataManager.getInstance().registerClass(new PlayerStatus(), true, true);
            StoreDataManager.getInstance().registerClass(new PlayerStatusExtended(), true, true);
            StoreDataManager.getInstance().registerClass(new ServerSessionConstant(), true, true);
            StoreDataManager.getInstance().registerClass(new ServerSessionConstantString(), true, true);
            StoreDataManager.getInstance().registerClass(new ServerSessionConstantInteger(), true, true);
            StoreDataManager.getInstance().registerClass(new ServerSessionConstantLong(), true, true);
        }


    }
}//package com.ankamagames.dofus.network

